### PR TITLE
Bug/73

### LINKED ISSUE #73: [BUG] - Join anonymous users
### Description

Should be able to join based on a top level endpoint /join

where they provide the code.

### Reproduction steps

```bash
No reproduction steps
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by KristianS93**
## Description

Fixed such that the join endpoint is on the root level "/join", where an id and code should be provided in the body.

### Resolved Issue
Fixes #73

## Changes

Changed endpoint. 
Changed the bruno folder to a hidden folder ".bruno" such that the folder does not confuse anybody, but can still be used.

## Checklist

- [X] New and old tests passed

### CODE REVIEW

File: Infrastructure/SessionRepository.cs [hunk 1]
```diff
@@ -141,6 +141,34 @@ JOIN session
...
+                    """;
+        using var con = await _connection.CreateConnectionAsync();
+        var session = await con.QueryFirstOrDefaultAsync<Session>(query, new { sessionCode });
+        if (session == null)
+        {
+            return null;
+        }
+        
+        var exercisesQuery = """
+                             SELECT e.exercise_id AS exerciseid, title AS exercisetitle FROM exercise AS e
```
Comment (JMyrtue) [inline Infrastructure/SessionRepository.cs:160]: Does not take description

**Review by JMyrtue — APPROVED** [review]
Left a single comment.

Apart from that, some out-commented sections could be removed.
